#!/bin/bash
_lvk=$(wget -qO- sshplus.xyz/script/versao)
IP=$(wget -qO- ipv4.icanhazip.com/)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
echo -e "$ipdovps" > /etc/IP
rm -rf /etc/SSHPlus/bot /etc/SSHPlus/ShellBot.sh /etc/SSHPlus/cabecalho /etc/SSHPlus/proxy.py > /dev/null 2>&1
echo -e "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
echo -e '1.2' > /usr/lib/ADMNETFREE && cat /usr/lib/ADMNETFREE > /usr/lib/ADMNETFREE
[[ ! -d /home/DATABASE ]] && mkdir /home/DATABASE
[[ ! -d /home/DATABASE/backups ]] && mkdir /home/DATABASE/backups
[[ ! -d /home/DATABASE/files ]] && mkdir /home/DATABASE/files
[[ ! -d /home/DATABASE/files/userteste ]] && mkdir /home/DATABASE/files/userteste
[[ ! -d /etc/ADMVPS ]] && mkdir /etc/ADMVPS
[[ ! -e /etc/SSHPlus ]] && mkdir /etc/SSHPlus
[[ ! -d /etc/SSHPlus/senha ]] && mkdir /etc/SSHPlus/senha
netstat -nplt| grep -w 'apache2' |grep -w '80' && sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf && service apache2 restart
[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
service ssh restart

wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/autorun -O /bin/autorun > /dev/null 2>&1
chmod +x /bin/autorun
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/badudp -O /bin/badudp > /dev/null 2>&1
chmod +x /bin/badudp
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/bannerssh -O /bin/bannerssh > /dev/null 2>&1
chmod +x /bin/bannerssh
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/blockuser -O /bin/blockuser > /dev/null 2>&1
chmod +x /bin/blockuser
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/criaruser -O /bin/criaruser > /dev/null 2>&1
chmod +x /bin/criaruser
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/expirados -O /bin/expirados > /dev/null 2>&1
chmod +x /bin/expirados
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/informacoes -O /bin/informacoes > /dev/null 2>&1
chmod +x /bin/informacoes
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/inst_dropbear -O /bin/inst_dropbear > /dev/null 2>&1
chmod +x /bin/inst_dropbear
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/inst_open -O /bin/inst_open > /dev/null 2>&1
chmod +x /bin/inst_open
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/inst_shadowsocks -O /bin/inst_shadowsocks > /dev/null 2>&1
chmod +x /bin/inst_shadowsocks
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/inst_socks -O /bin/inst_socks > /dev/null 2>&1
chmod +x /bin/inst_socks
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/inst_squid -O /bin/inst_squid > /dev/null 2>&1
chmod +x /bin/inst_squid
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/inst_sslstunel -O /bin/inst_sslstunel > /dev/null 2>&1
chmod +x /bin/inst_sslstunel
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/instalar -O /bin/instalar > /dev/null 2>&1
chmod +x /bin/instalar
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/limiterconex -O /bin/limiterconex > /dev/null 2>&1
chmod +x /bin/limiterconex
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/limitermenu -O /bin/limitermenu > /dev/null 2>&1
chmod +x /bin/limitermenu
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/limiterstart -O /bin/limiterstart > /dev/null 2>&1
chmod +x /bin/limiterstart
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/limparcache -O /bin/limparcache > /dev/null 2>&1
chmod +x /bin/limparcache
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/menubackup -O /bin/menubackup > /dev/null 2>&1
chmod +x /bin/menubackup
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/monitoring -O /bin/monitoring > /dev/null 2>&1
chmod +x /bin/monitoring
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/mudardata -O /bin/mudardata > /dev/null 2>&1
chmod +x /bin/mudardata
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/mudarsenha -O /bin/mudarsenha > /dev/null 2>&1
chmod +x /bin/mudarsenha
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/portas -O /bin/portas > /dev/null 2>&1
chmod +x /bin/portas
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/reiniciar_vps -O /bin/reiniciar_vps > /dev/null 2>&1
chmod +x /bin/reiniciar_vps
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/removebackup -O /bin/removebackup > /dev/null 2>&1
chmod +x /bin/removebackup
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/removeuser -O /bin/removeuser > /dev/null 2>&1
chmod +x /bin/removeuser
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/speedtest -O /bin/speedtest > /dev/null 2>&1
chmod +x /bin/speedtest
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/tcpspeed -O /bin/tcpspeed > /dev/null 2>&1
chmod +x /bin/tcpspeed
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/uninstall -O /bin/uninstall > /dev/null 2>&1
chmod +x /bin/uninstall
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/userdetalhes -O /bin/userdetalhes > /dev/null 2>&1
chmod +x /bin/userdetalhes
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/usermenu -O /bin/usermenu > /dev/null 2>&1
chmod +x /bin/usermenu
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/userteste -O /bin/userteste > /dev/null 2>&1
chmod +x /bin/userteste
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/velocidade -O /bin/velocidade > /dev/null 2>&1
chmod +x /bin/velocidade
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/proxy.py -O /etc/ADMVPS/proxy.py > /dev/null 2>&1
chmod +x /bin/proxy.py
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/REPOSITORIO-MANAGER/master/_armado_scripts/Modulos/pwd.pwd -O /etc/ADMVPS/pwd.pwd > /dev/null 2>&1
chmod +x /bin/pwd.pwd

_dir1='/bin'
_dir2='/etc/SSHPlus'
_mdls=("addhost" "delhost" "alterarsenha" "criarusuario" "expcleaner" "mudardata" "remover" "criarteste" "verifbot" "droplimiter" "alterarlimite" "ajuda" "sshmonitor" "badvpn" "userbackup" "blockt" "otimizar" "menu" "speedtest" "banner" "cfirm.py" "senharoot" "reiniciarservicos" "reiniciarsistema" "attscript" "conexao" "delscript" "detalhes" "botssh" "infousers" "verifatt" "limiter" "uexpired" "cabecalho" "bot" "proxy.py")
_arq_host="/etc/hosts"
_host[0]="d1n212ccp6ldpw.cloudfront.net"
_host[1]="dns.whatsapp.net"
_host[2]="portalrecarga.vivo.com.br/recarga"
_host[3]="navegue.vivo.com.br/controle/"
_host[4]="navegue.vivo.com.br/pre/"
_host[5]="www.whatsapp.net"
_host[6]="/SSHPLUS?"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done
crontab -r
[[ ! -e /etc/autostart ]] && {
echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
chmod +x /etc/autostart
} || {
[[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
for proc in $(ps x |grep 'dmS'|grep -v 'grep'|awk {'print $1'} ); do
screen -r -S "$proc" -X quit
done
screen -wipe > /dev/null
echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
chmod +x /etc/autostart
}
#INICIO
[[ $(crontab -l|grep -c "autostart") = '0' ]] && (crontab -l 2>/dev/null; echo "@reboot /etc/autostart") | crontab -
[[ $(crontab -l|grep -c "autostart") = '1' ]] && (crontab -l 2>/dev/null; echo "* * * * * /etc/autostart") | crontab -
echo "$_lvk" |sed -n '1 p' |cut -d' ' -f2 > /bin/versao && cat /bin/versao > /home/sshplus
service ssh restart > /dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart > /dev/null 2>&1
rm -rf $home/list > /dev/null 2>&1