#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

if [[ -e /etc/bash.bashrc-bakup ]]; then
	offautorun () {
mv -f /etc/bash.bashrc-bakup /etc/bash.bashrc
cat /etc/bash.bashrc | grep -v "/bin/h" > /tmp/bash
mv -f /tmp/bash /etc/bash.bashrc
}
clear
echo ""
echo -e "\033[1;32mDESATIVANDO AUTO EXECUÇÃO\033[0m"
echo ""
fun_bar 'offautorun'
echo ""
echo -e "\033[1;37mAUTO EXECUÇÃO\033[1;31m DESATIVADA!\033[0m"
sleep 1.5s
echo ""
usermenu
exit
elif [[ -e /etc/bash.bashrc ]]; then
	onautorun () {
cat /etc/bash.bashrc|grep -v /bin/h > /etc/bash.bashrc.2
echo '/bin/h' >> /etc/bash.bashrc.2
cp /etc/bash.bashrc /etc/bash.bashrc-bakup
mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
}
clear
echo ""
echo -e "\033[1;32mATIVANDO AUTO EXECUÇÃO\033[0m"
echo ""
fun_bar 'onautorun'
echo ""
echo -e "\033[1;37mAUTO EXECUÇÃO\033[1;32m ATIVADA!\033[0m"
sleep 1.5s
echo ""
usermenu
exit
fi