#!/bin/bash

fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
pid_badvpn=$(ps x | grep badvpn | grep -v grep | awk '{print $1}')
 echo""
if [ "$pid_badvpn" = "" ]; then
   
inst_udp () {
    if [[ ! -e /bin/badvpn-udpgw ]]; then
    cd $HOME
    wget https://www.dropbox.com/s/3ibigk2nyguadl9/badvpn-udpgw -o /dev/null
    mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
    chmod 777 /bin/badvpn-udpgw
    fi
  }
  clear
   echo""
   echo -e "\033[1;37mINSTALANDO BADVPN..."
   echo""
   fun_bar 'inst_udp'
   echo""
   echo -e "\033[1;32mINICIANDO O BADVPN... \033[0m\n"
	   fun_udpon2 () {
    screen -dmS screen /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10
    	}
    	fun_bar 'fun_udpon2'
    	echo""
    [[ "$(ps x | grep badvpn | grep -v grep | awk '{print $1}')" ]] && echo -e "\033[1;32m  BADVPN INICIADO!" || echo -e "\033[1;31mARQUITETURA NAO SUPORTADA!"
    echo""
    sleep 2
    h
    unset pid_badvpn
  exit


else
clear
echo""
echo -e "\033[1;37m  PARANDO BADVPN..."
echo""
fun_stopbad () {
    kill -9 $(ps x | grep badvpn | grep -v grep | awk '{print $1'}) > /dev/null 2>&1
    killall badvpn-udpgw > /dev/null 2>&1
  }
  fun_bar 'fun_stopbad'
  echo""
    [[ ! "$(ps x | grep badvpn | grep -v grep | awk '{print $1}')" ]] && echo -e "\033[1;31m   BADVPN PARADO!"
    echo""
    sleep 2
    h
    unset pid_badvpn
    exit
    fi