#!/bin/bash
linha="\033[0m\e[34m================================="  
clear
chk=$(cat /etc/ssh/sshd_config | grep Banner)
[[ $(netstat -nltp|grep 'dropbear' | wc -l) != '0' ]] && {
    local="/etc/bannerssh"
	[[ $(grep -wc $local /etc/default/dropbear) = '0' ]] && echo 'DROPBEAR_BANNER="/etc/bannerssh"' >>  /etc/default/dropbear
}
[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
	local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
} || {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/ssh/sshd_config) = '0' ]] && echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
}
echo -e "$linha"
echo -e "\033[1;37m       BEM VINDO AO BANNER"
echo -e "$linha"
echo -e "\033[01;31m 0\033[01;36m -\033[01;37m [ MENU INICIAL ]"
echo -e "\033[01;31m 1\033[01;36m -\033[1;32m ADICIONAR BANNER"
echo -e "\033[01;31m 2\033[01;36m -\033[1;32m REMOVER BANNER"
echo -e "$linha"
echo -ne "\033[1;37m OPÇÃO \033[1;31m0\033[1;36m-\033[1;31m2\033[1;37m:"; read resp
if [[ "$resp" = "1" ]]; then
echo -e "$linha"
echo -ne "\033[1;33m DIGITE O TEXTO\033[1;31m ->\033[1;37m : "; read  msg1
if [[ -z "$msg1" ]]; then
echo ""
echo -e "\033[1;31m Erro! \033[1;37mCampo vazio ou invalido !\033[0m"
sleep 2
bannerssh
fi
echo ""
echo -e "\033[1;37m ESCOLHA O TAMANHO DO TEXTO"
echo -e "$linha"
echo -e "\033[01;31m 1\033[01;36m -\033[1;32m FONTE PEQUENA"
echo -e "\033[01;31m 2\033[01;36m -\033[1;32m FONTE MEDIA"
echo -e "\033[01;31m 3\033[01;36m -\033[1;32m FONTE GRANDE"
echo -e "\033[01;31m 4\033[01;36m -\033[1;32m FONTE GIGANTE"
echo -e "$linha"
echo -ne "\033[1;37m OPÇÃO \033[1;31m1\033[1;36m-\033[1;31m4\033[1;37m:"; read opc
if [[ "$opc" = "1" ]] || [[ "$opc" = "01" ]]; then
_size='6'
elif [[ "$opc" = "2" ]] || [[ "$opc" = "02" ]]; then
_size='4'
elif [[ "$opc" = "3" ]] || [[ "$opc" = "03" ]]; then
_size='3'
elif [[ "$opc" = "4" ]] || [[ "$opc" = "04" ]]; then
_size='1'
fi
echo -e "$linha"
echo -e "\033[01;31m  1\033[01;36m -\033[1;32m AZUL"
echo -e "\033[01;31m  2\033[01;36m -\033[1;32m VERDE"
echo -e "\033[01;31m  3\033[01;36m -\033[1;32m VERMELHO"
echo -e "\033[01;31m  4\033[01;36m -\033[1;32m AMARELO"
echo -e "\033[01;31m  5\033[01;36m -\033[1;32m ROSA"
echo -e "\033[01;31m  6\033[01;36m -\033[1;32m CYANO"
echo -e "\033[01;31m  7\033[01;36m -\033[1;32m LARANJA"
echo -e "\033[01;31m  8\033[01;36m -\033[1;32m ROXO"
echo -e "\033[01;31m  9\033[01;36m -\033[1;32m PRETO"
echo -e "\033[01;31m 10\033[01;36m -\033[1;32m SEM COR"
echo -e "$linha"
echo -ne "\033[1;37m QUAL A COR \033[1;31m1\033[1;36m-\033[1;31m10\033[1;37m:"; read ban_cor
if [[ "$ban_cor" = "1" ]] || [[ "$ban_cor" = "01" ]]; then
echo "<h$_size><font color='blue'>$msg1" >> $local
elif [[ "$ban_cor" = "2" ]] || [[ "$ban_cor" = "02" ]]; then
echo "<h$_size><font color='green'>$msg1" >> $local
elif [[ "$ban_cor" = "3" ]] || [[ "$ban_cor" = "03" ]]; then
echo "<h$_size><font color='red'>$msg1" >> $local
elif [[ "$ban_cor" = "4" ]] || [[ "$ban_cor" = "04" ]]; then
echo "<h$_size><font color='yellow'>$msg1" >> $local
elif [[ "$ban_cor" = "5" ]] || [[ "$ban_cor" = "05" ]]; then
echo "<h$_size><font color='#F535AA'>$msg1" >> $local
elif [[ "$ban_cor" = "6" ]] || [[ "$ban_cor" = "06" ]]; then
echo "<h$_size><font color='cyan'>$msg1" >> $local
elif [[ "$ban_cor" = "7" ]] || [[ "$ban_cor" = "07" ]]; then
echo "<h$_size><font color='#FF7F00'>$msg1" >> $local
elif [[ "$ban_cor" = "8" ]] || [[ "$ban_cor" = "08" ]]; then
echo "<h$_size><font color='#9932CD'>$msg1" >> $local
elif [[ "$ban_cor" = "9" ]] || [[ "$ban_cor" = "09" ]]; then
echo "<h$_size><font color='black'>$msg1" >> $local
elif [[ "$ban_cor" = "10" ]]; then
echo "<h$_size>$msg1</h$_size>" >> $local
/etc/init.d/ssh restart > /dev/null 2>&1
echo -e "\n\033[1;32m BANNER DEFINIDO !\033[0m"
sleep 2
usermenu
else
echo ""
echo -e "\033[1;31m Erro! \033[1;37mOpcao invalida ! Tente novamente.\033[0m"
sleep 2
bannerssh
fi
echo "</font></h$_size>" >> $local
service ssh restart > /dev/null 2>&1 &
service sshd restart > /dev/null 2>&1 & 
service dropbear restart > /dev/null 2>&1 &
/etc/init.d/stunnel4 restart > /dev/null 2>&1
echo -e "\n\033[1;32m BANNER DEFINIDO !\033[0m"
sleep 2
usermenu
unset ban_cor
elif [[ "$resp" = "2" ]]; then
echo " " > $local
echo -e "\n\033[1;31m BANNER EXCLUIDO !\033[0m"
service ssh restart > /dev/null 2>&1 &
service sshd restart > /dev/null 2>&1 & 
service dropbear restart > /dev/null 2>&1 &
/etc/init.d/stunnel4 restart > /dev/null 2>&1
sleep 2
usermenu
elif [[ "$resp" = "0" ]]; then
usermenu
else
echo ""
echo -e "\033[1;31m Erro! \033[1;37mOpcao invalida ! Tente novamente.\033[0m"
sleep 2
bannerssh
fi