#!/bin/bash
linha="\033[0m\e[34m========================================"  
USERS_DATABASE="/root/usuarios.db"  
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/blockuser > /dev/null 2>&1  
block_userfun () {
local USRloked="/home/DATABASE/ADMVPS-userlock"
if [[ $(cat ${USRloked}|grep -w "$1") ]]; then
usermod -U "$1" &>/dev/null
[[ -e ${USRloked} ]] && {
newbase=$(cat ${USRloked}|grep -w -v "$1")
[[ -e ${USRloked} ]] && rm ${USRloked}
for value in `echo ${newbase}`; do
echo $value >> ${USRloked}
done
}

return 1
else
usermod -L "$1" &>/dev/null
echo $1 >> ${USRloked}
return 0
fi
}
block_user () {
	
local USRloked="/home/DATABASE/ADMVPS-userlock"
[[ ! -e ${USRloked} ]] && touch ${USRloked}
clear
echo -e "$linha"
echo -e "\033[01;37m   BLOQUEIO E DESBLOQUEIO DE USUARIO " 
echo -e "$linha"
USERS_NUMBER=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)
if [ $USERS_NUMBER = "0" ]; then
echo -e "\033[01;37mNenhum usuário criado no momento!"
echo -e "$linha"
echo -ne "\033[01;36mDESEJA CRIAR UM USUARIO?\033[01;32m [s/n]:\033[01;37m "; read CREATE
      
 if [ "$CREATE" = "s" ]; then   
       criaruser
 elif [ "$CREATE" = "n" ]; then
       usermenu
 else
       removeuser
 fi
else
i=0
echo -e "\033[01;37m 0:\033[01;32m RETORNAR AO MENU."
echo ""
for USERS in `awk -F : '$3 > 900 { print $1 }' /etc/passwd | grep -v "nobody" |grep -vi polkitd |grep -vi system-`; do
i=$(expr $i + 1)
oP+=$i
oP+=":$USERS\n"
if [[ $(cat ${USRloked}|grep -w "${USERS}") ]]; then
USERS=$(printf '%-10s' "${USERS}")
echo -ne "\033[1;31m $i\033[1;36m -" && echo -e "\033[1;33m ${USERS} \033[1;31mBloqueado"
else
USERS=$(printf '%-10s' "${USERS}")
echo -ne "\033[1;31m $i\033[1;36m -" && echo -e "\033[1;33m ${USERS} \033[1;32mDesbloqueado"
fi

done 
  
echo -e "$linha"
num=$(cat $USERS_DATABASE | wc -l)
echo -ne "\033[1;36m Nome ou N° do Usuario \033[1;31m1\033[1;37m-\033[1;31m$num\033[1;37m: " ; read NUMBER
if [[ -z $NUMBER ]]; then
echo ""
echo -e "\033[1;31mErro! \033[1;37mVoce nao digitou um nome de usuario! Tente novamente.\033[0m"
sleep 2s
blockuser
exit
else
if [ "$NUMBER" = "0" ]; then
usermenu
exit
else
USER=$(echo -e "$oP" | grep -E "\b$NUMBER\b" | cut -d: -f2)
if [[ -z $USER ]]; then
	echo ""
echo -e "\033[1;31mErro! \033[1;37mEste usuario e inexistente na lista de usuarios! Tente novamente.\033[0m"
sleep 2s
blockuser
exit
else
echo""
echo -ne "\033[1;33m Usuario : " && echo -ne "\033[1;37m$USER "
block_userfun "$USER" &&echo -e "\033[1;37m [\033[1;31m Bloqueado\033[1;37m ]" || echo -e "\033[1;37m [\033[1;32m Desbloqueado\033[1;37m ]"
pkill -f $USER 1> /dev/null 2> /dev/null
sleep 2
echo ""  
blockuser
exit
fi
fi
fi
fi

}

block_user