#!/bin/bash
USERS_DATABASE="/root/usuarios.db"
linha="\033[0m\e[34m========================================"  
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/criaruser > /dev/null 2>&1  
__IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
newclient () {
#Nome #Senha
usermod -p $(openssl passwd -1 $2) $1
  while [[ ${newfile} != @(s|S|y|Y|n|N) ]]; do
  echo -ne "\033[01;36mCRIAR ARQUIVO OpenVpn?\033[01;32m [s/n]\033[01;37m:"; read newfile
  done
if [[ ${newfile} = @(s|S) ]]; then
	cd /etc/openvpn/easy-rsa/
	./easyrsa build-client-full $1 nopass > /dev/null 2>&1
  cp /etc/openvpn/client-common.txt ~/$1.ovpn
	echo "<ca>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$1.ovpn
	echo "</ca>" >> ~/$1.ovpn
	echo "<cert>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> ~/$1.ovpn
	echo "</cert>" >> ~/$1.ovpn
	echo "<key>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/private/$1.key >> ~/$1.ovpn
	echo "</key>" >> ~/$1.ovpn
	echo "<tls-auth>" >> ~/$1.ovpn
	cat /etc/openvpn/ta.key >> ~/$1.ovpn
	echo "</tls-auth>" >> ~/$1.ovpn
  while [[ ${ovpnauth} != @(s|S|y|Y|n|N) ]]; do
  	echo -ne "\033[01;36mARQUIVO COM SENHA?\033[01;32m [s/n]\033[01;37m:"; read ovpnauth
    
  done
  [[ ${ovpnauth} = @(n|N) ]] && sed -i "s;auth-user-pass;<auth-user-pass>\n$1\n$2\n</auth-user-pass>;g" $HOME/$1.ovpn
  cd $HOME
  zip ./$1.zip ./$1.ovpn > /dev/null 2>&1
  echo ""
  echo -e "\033[1;32mArquivo Criado em\033[01;37m: ($HOME/$1.zip)"
  echo ""
  sleep 3
 fi
}

clear
echo -e "$linha"
echo -e "\033[01;37m      LISTA DE USUÁRIOS CRIADOS "
echo -e "$linha"
USERS_NUMBER=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)
if [ $USERS_NUMBER = "0" ]; then
  echo -e "\033[01;37mNenhum usuário criado no momento!"
else
  for USERS in `awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort`; do
    echo -ne "\033[01;33m"; echo $USERS
  done
fi
echo ""
echo -e "\033[01;32m 0: RETORNAR AO MENU."
echo -e "$linha"
echo -ne "\033[01;36mNOME DO USUÁRIO:\033[01;37m"; read USER
if [ -z $USER ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê não digitou um nome de usuário! Tente novamente.\033[0m"
  sleep 2s
  criaruser
  exit
else
if [ "$USER" = "root" ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mUsuário inválido! Tente novamente.\033[0m"
  sleep 3s
  criaruser
  exit
else
if [ "$USER" = "0" ]; then
  usermenu
  exit
else
if [ "$USER" = "R" ]; then
  criaruser
  exit
else
if echo $USER | grep -q '[^a-z A-Z 0-9 ._-]'; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê digitou um nome de usuário inválido! Use apenas letras, números\033[0m"; echo -e "\033[01;37;41mpontos e traços. Não use espaços, acentos ou caracteres especiais. T\033[0m"; echo -e "\033[01;37;41mente novamente.                                                     \033[0m"
  sleep 2s
  criaruser
  exit
else
  awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort > /tmp/users.txt
if grep -xq "$USER" /tmp/users.txt; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mEste usuário já existe na lista de usuários! Tente novamente.\033[0m"
  sleep 1s
  criaruser
  exit
else

CHARACTERSMIN=$(echo ${#USER})
if [ $CHARACTERSMIN -lt 4 ]; then
  echo "" 
  echo -e "\033[1;31mErro! \033[1;37mVocê digitou um nome de usuário muito curto, use no mínimo 4 caracteres!\033[0m"
  echo " "
  sleep 2s
  criaruser
  exit
else
  CHARACTERS=$(echo $USER | wc -c)
if [ $CHARACTERS -gt 33 ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê digitou um nome de usuário muito grande! Use no máximo 3\033[0m"; echo -e "\033[01;37;41m2 caracteres para o usuário. Tente novamente.                \033[0m"
  sleep 2s
  criaruser
  exit
else
  echo -ne "\033[01;36mSENHA:\033[01;37m"; read PASSWORD
if [ -z $PASSWORD ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê não digitou uma senha! Tente novamente.\033[0m"
  sleep 1s
  criaruser
  exit
else
if [ "$PASSWORD" = "0" ]; then
  usermenu
  exit
else
if [ "$PASSWORD" = "R" ]; then
  criaruser
  exit
else
  echo -ne "\033[01;36mN° DE DIAS PARA EXPIRAR:\033[01;37m"; read DAYS
if echo $DAYS | grep -q '[^0-9R]'; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê digitou um número de dias inválido! Tente novamente.\033[0m"
  sleep 3s
  criaruser
  exit
else
if [ -z $DAYS ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê não digitou um número! Tente novamente.\033[0m"
  sleep 1s
  criaruser
  exit
else
if [ "$DAYS" = "0" ]; then
  usermenu
  exit
else
if [ "$DAYS" = "R" ]; then
  criaruser
  exit
else
  echo -ne "\033[01;36mN° DE CONEXÕES PERMITIDAS:\033[01;37m"; read CONNECTIONS
if echo $CONNECTIONS | grep -q '[^0-9R]'; then
  echo ""
  echo -e "\033[01;37;41mVocê digitou um número inválido! Tente novamente.\033[0m"
  sleep 1s
  criaruser
  exit
else
if [ -z $CONNECTIONS ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê não digitou um número! Tente novamente.\033[0m"
  sleep 1s
  criaruser
  exit
else
if [ "$CONNECTIONS" = "0" ]; then
  usermenu
  exit
else
if [ "$CONNECTIONS" = "R" ]; then
  criaruser
  exit
else
  VALIDITY1=$(date "+%Y-%m-%d" -d "+ $DAYS days")
  VALIDITY2=$(date "+%d/%m/%Y" -d "+ $DAYS days")
  useradd -e $VALIDITY1 -M -s /bin/false $USER
  (echo $PASSWORD; echo $PASSWORD) | passwd $USER 1> /dev/null 2> /dev/null
  echo "$PASSWORD" > /etc/SSHPlus/senha/$USER
  echo "$USER $CONNECTIONS" >> $USERS_DATABASE
  [[ $(dpkg --get-selections|grep -w "openvpn"|head -1) ]] && [[ -e /etc/openvpn/openvpn-status.log ]] && newclient "$USER" "$PASSWORD"
  clear
  echo -e "$linha"
  echo -e "\033[01;37m       USÚARIO CRIADO COM SUCESSO!"
  echo -e "$linha"
  echo -e "\033[01;36mUsuário:\033[01;37m $USER"
  echo -e "\033[01;36mSenha:\033[01;37m $PASSWORD"
  echo -e "\033[01;36mValidade:\033[01;37m $VALIDITY2 às \033[01;31m00:00:00"
  echo -e "\033[01;36mConexões permitidas:\033[01;37m $CONNECTIONS"
  echo -e "\033[01;36mConta SSH:\033[01;37m $__IP"
  echo -e "$linha"
  echo ""
  read -p "$(echo -e "\033[01;37mDeseja criar mais um usuário?\033[01;32m [s/n]:\033[01;37m")" -e -i n resp
	if [ "$resp" == "s" ]; then
	criaruser
	elif [ "$resp" == "n" ]; then
	h
  exit
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi
fi


													