#!/bin/bash
USERS_DATABASE="/home/DATABASE/files/users.db"
linha="\033[0m\e[34m============================================="  
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/expirados > /dev/null 2>&1  
clear
echo -e "$linha"
echo -e "\033[01;33m   LISTA DE USUÁRIOS E DATAS DE EXPIRAÇÃO:"
echo -e "$linha"
USERS_NUMBER=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)

if [ $USERS_NUMBER = "0" ]; then
  echo -e "\033[01;37mNenhum usuário criado no momento!"
  echo -e "$linha"
  echo -ne "\033[01;36mDESEJA CRIAR UM USUARIO?\033[01;32m [s/n]:\033[01;37m "; read CREATE
      
      if [ "$CREATE" = "s" ]; then
          criaruser
          exit
      elif [ "$CREATE" = "n" ]; then
          usermenu
          exit
      else
          expirados
          exit
      fi

else
  for USERS in `awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort`; do
    EXPIRATION=$(chage -l $USERS | grep -E "Account expires" | cut -d " " -f3-)
    if [[ $EXPIRATION = "never" ]]; then
      echo -ne "\033[01;33m$(printf '%-11s%s\n' " $USERS" )"; echo -ne "\033[01;37m 00/00/0000"; echo -e "\033[01;32m (ATIVO) [Não removido]"
    else
      DATE_BR=$(date -d "$EXPIRATION" '+%Y%m%d')
      TODAY=$(date -d today '+%Y%m%d')
    if [ $TODAY -ge $DATE_BR ]; then
      DATE=$(date -d "$EXPIRATION" '+%d/%m/%Y')
      echo -ne "\033[01;33m$(printf '%-11s%s\n' " $USERS")"; echo -ne "\033[01;37m $DATE"; echo -e "\033[01;31m (VENCEU) [Removido]"
      pkill -f $USERS
      userdel $USERS
      cat $USERS_DATABASE | grep -wv "$USERS" > remove.txt
      mv remove.txt $USERS_DATABASE
    else
      DATE=$(date -d "$EXPIRATION" '+%d/%m/%Y')
      echo -ne "\033[01;33m$(printf '%-11s%s\n' " $USERS")"; echo -ne "\033[01;37m $DATE"; echo -e "\033[01;32m (ATIVO) [Não removido]"
    fi
    fi
  done
fi
echo -e "$linha"
echo -ne "\033[1;31m ENTER \033[1;33mpara retornar ao \033[1;32mMENU!"
read ENTER
usermenu
exit