#!/bin/bash
linha="\033[0m\e[34m================================="  
BASE="/home/DATABASE"
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31mx"
   sleep 0.1s
   done
   [[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/limitermenu > /dev/null 2>&1  
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

clear
#limiter
function limit1 () {
   clear
   echo ""
   echo -e "\n\033[1;32mINICIANDO O LIMITER... \033[0m"
   echo ""
   fun_bar 'screen -dmS limiterstart limiterstart' 'sleep 3'
   echo -e "\n\033[1;32mLIMITER ATIVO !\033[0m"
   sleep 3
   h
   exit
}
function limit2 () {
   clear
   echo ""
   echo -e "\033[1;31mPARANDO O LIMITER... \033[0m"
   echo ""
   fun_stplimiter () {
      sleep 1
      screen -r -S "limiterstart" -X quit
      screen -wipe 1>/dev/null 2>/dev/null     
      [[ -e ${BASE}/USRonlines ]] && rm ${BASE}/USRonlines
      [[ -e ${BASE}/USRexpired ]] && rm ${BASE}/USRexpired
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n\033[1;31mLIMITER PARADO !\033[0m"
   sleep 3
   h
   exit 
}
function limit_ssh () {
[[ $(ps x | grep "limiterstart"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}
limit_ssh
exit