#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31mx"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[0m\e[34m======================================\033[0m"
echo -e "\033[0m\e[37m       LIMPEZA DE MEMORIA CACHE                "           
echo -e "\033[0m\e[34m======================================\033[0m"

echo ""
echo -e "\033[1;36mCORRIGINDO PROBLEMAS NAS DEPENDÊNCIAS"
echo""
fun_bar 'apt-get -f install'
echo""
echo -e "\033[1;36mREMOVENDO PACOTES INÚTEIS"
echo ""
fun_bar 'apt-get autoremove -y' 'apt-get autoclean -y'
echo ""
echo -e "\033[1;36mREMOVENDO PACOTES COM PROBLEMAS"
echo ""
fun_bar 'apt-get -f remove -y' 'apt-get clean -y'


fun_limpram () {
sync 
echo 3 > /proc/sys/vm/drop_caches
sleep 4
sync && sysctl -w vm.drop_caches=3
sysctl -w vm.drop_caches=0
swapoff -a
swapon -a
sleep 4
}
function aguarde {
sleep 1
helice ()
{
	fun_limpram > /dev/null 2>&1 & 
	tput civis
	while [ -d /proc/$! ]
	do
		for i in / - \\ \|
		do
			sleep .1
			echo -ne "\e[1D$i"
		done
	done
	tput cnorm
}
echo""
echo -ne "\033[1;36mLIMPANDO MEMORIA \033[1;32mRAM \033[1;37me \033[1;32mSWAP\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
helice
echo -e "\e[1DOk"
}
aguarde
sleep 1.5s
echo""
echo -e "\033[0m\e[34m======================================\033[0m"
echo""
echo -e "\033[1;32mPROCESSO CONCLUIDO"
echo""
sleep 2
usermenu
exit