#!/bin/bash
USERS_DATABASE="/root/usuarios.db"
linha="\033[0m\e[34m========================================"  
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/mudarsenha > /dev/null 2>&1  
clear
echo -e "$linha"
 echo -e "\033[01;37m LISTA DE USUÁRIOS E SENHAS DE ACESSO" 
echo -e "$linha"
USERS_NUMBER=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)
if [ $USERS_NUMBER = "0" ]; then
echo -e "\033[01;37mNenhum usuário criado no momento!"
echo -e "$linha"
echo -ne "\033[01;36mDESEJA CRIAR UM USUARIO?\033[01;32m [s/n]:\033[01;37m "; read CREATE
      
      if [ "$CREATE" = "s" ]; then
          criaruser
      elif [ "$CREATE" = "n" ]; then
          usermenu
      else
           mudarsenha
      fi
else
i=0
echo -e "\033[01;37m 0:\033[01;32m RETORNAR AO MENU."
echo ""
for USERS in `awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort`; do
i=$(expr $i + 1)
oP+=$i
oP+=":$USERS\n"
if [[ -e "/etc/SSHPlus/senha/$USERS" ]]; then
		_senha="$(cat /etc/SSHPlus/senha/$USERS)"
	else
		_senha='Null'
	fi
	
USERS=$(printf '%-14s%s\n' "$USERS")
echo -e "\033[1;31m $i \033[1;37m- \033[1;37m$USERS  \033[1;33mSenha\033[1;32m:\033[1;37m $_senha\033[0m"
done < "$USERS_DATABASE"
echo -e "$linha"
num_user=$(cat $USERS_DATABASE | wc -l)
  echo -ne "\033[1;36mNome ou N° do Usuario \033[1;31m 1\033[1;37m-\033[1;31m$num_user\033[1;37m: " ; read NUMBER
if [ -z $NUMBER ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê não digitou um nome de usuário! Tente novamente.\033[0m"
  sleep 2s
  mudarsenha
  exit
else
if [ "$NUMBER" = "0" ]; then
  usermenu
  exit
fi
USER=$(echo -e "$oP" | grep -E "\b$NUMBER\b" | cut -d: -f2)
if [ -z $USER ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mEste usuario e inexistente na lista de usuarios! Tente novamente.\033[0m"
  sleep 2s
  mudarsenha
  exit
else

  if [[ `grep -c /$USER: /etc/passwd` -ne 0 ]]
  then
  	echo ""
  	echo -e "\033[01;36mNome do usuário:\033[01;37m $USER"
    echo -ne "\033[01;36mNova senha:\033[01;37m "; read PASSWORD
if [ -z $PASSWORD ]; then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê não digitou uma nova senha! Tente novamente.\033[0m"
  sleep 2s
  mudarsenha
  exit
else
if [ "$PASSWORD" = "0" ]; then
  usermenu
  exit
else

  echo "$PASSWORD" > /etc/SSHPlus/senha/$USER
  pkill -f $USER 1> /dev/null 2> /dev/null
  (echo $PASSWORD; echo $PASSWORD) | passwd $USER 1> /dev/null 2> /dev/null
  echo ""
  echo -e "\033[01;32mSenha do usuário alterada com sucesso!"
  
  
  echo -e "\033[01;36mSenha alterada para:\033[01;37m $PASSWORD"
  echo ""
  read -p "$(echo -e "\033[01;37mMudar senha de mais um?\033[01;32m [s/n]:\033[01;37m")" -e -i n resp
	if [ "$resp" == "s" ]; then
	mudarsenha
	elif [ "$resp" == "n" ]; then
	h
  echo ""
  exit
fi
fi
fi
fi
fi
fi
fi
  
  