#!/bin/bash
USERS_DATABASE="/root/usuarios.db"
linha="\033[0m\e[34m========================================"  
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/mudardata > /dev/null 2>&1         
clear
  echo -e "$linha"
  echo -e "\033[01;37m LISTA DE USUÁRIOS E DATA DE EXPIRAÇÃO"
   echo -e "$linha"
USERS_NUMBER=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)
if [ $USERS_NUMBER = "0" ]; then
  echo -e "\033[01;37mNenhum usuário criado no momento!"
  echo -e "$linha"
  echo -ne "\033[01;36mDESEJA CRIAR UM USUARIO?\033[01;32m [s/n]:\033[01;37m "; read CREATE
      
      if [ "$CREATE" = "s" ]; then
          criaruser
      elif [ "$CREATE" = "n" ]; then
          usermenu
      else
          mudardata
      fi
else
  echo -e "\033[01;37m 0:\033[01;32m RETORNAR AO MENU."
  echo ""
tput setaf 7 ; tput bold 
list_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
i=0
i=0
unset _userPass
while read user; do
	i=$(expr $i + 1)
	_oP=$i
	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
	expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"
if [[ $expire == "never" ]]
	then
	echo -e "\033[1;31m $i \033[1;37m- \033[1;33m$user     \033[1;37m  00/00/0000\033[1;32m     S/DATA\033[0m"
else
		databr="$(date -d "$expire" +"%Y%m%d")"
		hoje="$(date -d today +"%Y%m%d")"
if [ $hoje -ge $databr ]
		then
			_user=$(echo -e "\033[1;31m $i \033[1;37m- \033[1;33m$user\033[1;37m")
			datanormal="$(date -d"$expire" '+%d/%m/%Y')"
			expired=$(echo -e "\033[1;31mVENCEU\033[0m")
			printf '%-45s%-15s%s\n' "$_user" "$datanormal" "$expired"
	echo "exp" > /tmp/exp
else
			_user=$(echo -e "\033[1;31m $i \033[1;37m- \033[1;33m$user\033[1;37m")
			datanormal="$(date -d"$expire" '+%d/%m/%Y')"
			ative=$(echo -e "\033[1;32mATIVO\033[0m")
			printf '%-45s%-15s%s\n' "$_user" "$datanormal" "$ative"
fi
fi
	_userPass+="\n${_oP}:${user}"
done <<< "${list_user}"
tput sgr0
   echo -e "$linha"
if [ -a /tmp/exp ]
then
	rm /tmp/exp
fi
num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
  echo -ne "\033[1;36m Nome ou N° do Usuario \033[1;31m 1\033[1;37m-\033[1;31m$num_user\033[1;37m: " ; read option
if [ "$option" = "0" ]; then
  usermenu
  exit
else
if [[ -z $option ]]
then
	echo ""
  echo -e "\033[1;31mErro! \033[1;37mEste usuario e inexistente na lista de usuarios! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
fi
usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
if [[ -z $usuario ]]
then
  echo ""
  echo -e "\033[1;31mErro! \033[1;37mEste usuário é inexistente na lista de usuários! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
else
if [[ `grep -c /$usuario: /etc/passwd` -ne 0 ]]
	then
  echo ""
	echo -e "\033[1;31mEX:\033[1;33m(\033[1;32mDATA: \033[1;37mDIA/MÊS/ANO \033[1;33mOU \033[1;32mDIAS: \033[1;37m30\033[1;33m)"
	echo ""
	echo -ne "\033[1;36mNova data ou dias para o usuario \033[1;33m$usuario: \033[1;37m"; read inputdate
if [[ "$(echo -e "$inputdate" | grep -c "/")" = "0" ]]; then 
	    	udata=$(date "+%d/%m/%Y" -d "+$inputdate days")
	    	sysdate="$(echo "$udata" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
else
	    	udata=$(echo -e "$inputdate")
	    	sysdate="$(echo "$inputdate" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
fi
if (date "+%Y-%m-%d" -d "$sysdate" > /dev/null  2>&1)
		then
if [[ -z $inputdate ]]
			then
	echo ""
  echo -e "\033[1;31mErro! \033[1;37mVoce digitou uma data invalida! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
else
if (echo $inputdate | egrep [^a-zA-Z] &> /dev/null)
				then
					today="$(date -d today +"%Y%m%d")"
					timemachine="$(date -d "$sysdate" +"%Y%m%d")"
if [ $today -ge $timemachine ]
					then
	echo ""
  echo -e "\033[1;31mErro! \033[1;37mVoce digitou uma data invalida! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
else
	chage -E $sysdate $usuario
	echo ""
  echo -e "\033[01;32mData de expiracao do usuario alterada com sucesso!"
  echo ""
  echo -e "\033[01;36mNome do usuario:\033[01;37m $usuario"
  echo -e "\033[01;36mData de expiracao alterada para:\033[01;37m $udata"
  echo ""
  read -p "$(echo -e "\033[01;37mMudar data de mais um?\033[01;32m [s/n]:\033[01;37m")" -e -i n resp
	if [ "$resp" == "s" ]; then
	mudardata
	elif [ "$resp" == "n" ]; then
	h
  echo ""
  exit
fi					
fi
else
	echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê digitou uma data invalida! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
fi
fi
else
	echo ""
  echo -e "\033[1;31mErro! \033[1;37mVocê digitou uma data invalida! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
fi
else
	echo ""
  echo -e "\033[1;31mErro! \033[1;37mEste usuario é inexistente na lista de usuarios! Tente novamente.\033[0m"
  sleep 1s
  mudardata
  exit
fi
fi
fi
fi
