#!/bin/bash

linha="\033[0m\e[34m================================="  
mine_port () {
local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
local NOREPEAT
local reQ
local Port
while read port; do
reQ=$(echo ${port}|awk '{print $1}')
Port=$(echo {$port} | awk '{print $9}' | awk -F ":" '{print $2}')
[[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
NOREPEAT+="$Port\n"
case ${reQ} in
squid|squid3)
[[ -z $SQD ]] && local SQD="\033[1;32m SERVICO\033[1;31m SQUID\033[1;32m PORTA \033[1;37m"
SQD+="$Port ";;
apache|apache2)
[[ -z $APC ]] && local APC="\033[1;32m SERVICO\033[1;31m APACHE\033[1;32m PORTA \033[1;37m"
APC+="$Port ";;
ssh|sshd)
[[ -z $SSH ]] && local SSH="\033[1;32m SERVICO\033[1;31m SSH\033[1;32m PORTA \033[1;37m"
SSH+="$Port ";;
dropbear)
[[ -z $DPB ]] && local DPB="\033[1;32m SERVICO\033[1;31m DROPBEAR\033[1;32m PORTA \033[1;37m"
DPB+="$Port ";;
ssserver)
[[ -z $SSV ]] && local SSV="\033[1;32m SERVICO\033[1;31m SHADOWSOCKS\033[1;32m PORTA \033[1;37m"
SSV+="$Port ";;
openvpn)
[[ -z $OVPN ]] && local OVPN="\033[1;32m SERVICO\033[1;31m OPENVPN\033[1;32m PORTA \033[1;37m"
OVPN+="$Port ";;
stunnel4|stunnel)
[[ -z $SSL ]] && local SSL="\033[1;32m SERVICO\033[1;31m SSL\033[1;32m PORTA \033[1;37m"
SSL+="$Port ";;
python|python3)
[[ -z $PY3 ]] && local PY3="\033[1;32m SERVICO\033[1;31m SOCKS\033[1;32m PORTA \033[1;37m"
PY3+="$Port ";;
esac
done <<< "${portasVAR}"
[[ ! -z $SQD ]] && echo -e $SQD
[[ ! -z $APC ]] && echo -e $APC
[[ ! -z $SSH ]] && echo -e $SSH
[[ ! -z $DPB ]] && echo -e $DPB
[[ ! -z $OVPN ]] && echo -e $OVPN
[[ ! -z $PY3 ]] && echo -e $PY3
[[ ! -z $SSL ]] && echo -e $SSL
[[ ! -z $SSV ]] && echo -e $SSV
}
port () {
local portas
local portas_var=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
i=0
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e ${portas}|grep -w "$var1 $var2")" ]] || {
    portas+="$var1 $var2 $portas"
    echo "$var1 $var2"
    let i++
    }
done <<< "$portas_var"
}
verify_port () {
local SERVICE="$1"
local PORTENTRY="$2"
[[ ! $(echo -e $(port|grep -v ${SERVICE})|grep -w "$PORTENTRY") ]] && return 0 || return 1
}
edit_squid () {
clear
echo ""
echo -e "\033[01;33m ESCOLHA AS PORTAS PARA O SQUID"
if [[ -e /etc/squid/squid.conf ]]; then
local CONF="/etc/squid/squid.conf"
elif [[ -e /etc/squid3/squid.conf ]]; then
local CONF="/etc/squid3/squid.conf"
fi
NEWCONF="$(cat ${CONF}|grep -v "http_port")"
echo -ne "\033[1;37m NOVA PORTA\033[1;33m:\033[1;37m "; read newports
for PTS in `echo ${newports}`; do
verify_port squid "${PTS}" && echo -e "\033[1;33m Port $PTS \033[1;32mOK" || {
echo -e "\033[1;33m Port $PTS \033[1;31mFAIL"
return 1
}
done
rm ${CONF}
while read varline; do
echo -e "${varline}" >> ${CONF}
 if [[ "${varline}" = "#portas" ]]; then
  for NPT in $(echo ${newports}); do
  echo -e "http_port ${NPT}" >> ${CONF}
  done
 fi
done <<< "${NEWCONF}"
echo -e "\033[01;37m AGUARDE"
service squid restart &>/dev/null
service squid3 restart &>/dev/null
sleep 1s
echo ""
echo -e "\033[01;32m PORTAS REDEFINIDAS"
echo ""
sleep 2s
h
exit
}
edit_apache () {
clear
echo ""
echo -e "\033[01;33m ESCOLHA AS PORTAS PARA O APACHE"
local CONF="/etc/apache2/ports.conf"
local NEWCONF="$(cat ${CONF})"
echo -ne "\033[1;37m NOVA PORTA\033[1;33m:\033[1;37m "; read newports
for PTS in `echo ${newports}`; do
verify_port apache "${PTS}" && echo -e "\033[1;33m Port $PTS \033[1;32mOK" || {
echo -e "\033[1;33m Port $PTS \033[1;31mFAIL"
return 1
}
done
rm ${CONF}
while read varline; do
if [[ $(echo ${varline}|grep -w "Listen") ]]; then
 if [[ -z ${END} ]]; then
 echo -e "Listen ${newports}" >> ${CONF}
 END="True"
 else
 echo -e "${varline}" >> ${CONF}
 fi
else
echo -e "${varline}" >> ${CONF}
fi
done <<< "${NEWCONF}"
echo -e "\033[01;37m AGUARDE"
service apache2 restart &>/dev/null
sleep 1s
echo ""
echo -e "\033[01;32m PORTAS REDEFINIDAS"
echo ""
sleep 2s
h
exit
}
edit_openvpn () {
clear
echo ""
echo -e "\033[01;33m ESCOLHA AS PORTAS PARA O OPENVPN"
local CONF="/etc/openvpn/server.conf"
local CONF2="/etc/openvpn/client-common.txt"
local NEWCONF="$(cat ${CONF}|grep -v [Pp]ort)"
local NEWCONF2="$(cat ${CONF2})"
echo -ne "\033[1;37m NOVA PORTA\033[1;33m:\033[1;37m "; read newports
for PTS in `echo ${newports}`; do
verify_port openvpn "${PTS}" && echo -e "\033[1;33m Port $PTS \033[1;32mOK" || {
echo -e "\033[1;33m Port $PTS \033[1;31mFAIL"
return 1
}
done
rm ${CONF}
while read varline; do
echo -e "${varline}" >> ${CONF}
if [[ ${varline} = "proto tcp" ]]; then
echo -e "port ${newports}" >> ${CONF}
fi
done <<< "${NEWCONF}"
rm ${CONF2}
while read varline; do
if [[ $(echo ${varline}|grep -v "remote-random"|grep "remote") ]]; then
echo -e "$(echo ${varline}|cut -d' ' -f1,2) ${newports} $(echo ${varline}|cut -d' ' -f4)" >> ${CONF2}
else
echo -e "${varline}" >> ${CONF2}
fi
done <<< "${NEWCONF2}"
echo -e "\033[01;37m AGUARDE"
service openvpn restart &>/dev/null
/etc/init.d/openvpn restart &>/dev/null
sleep 1s
echo ""
echo -e "\033[01;32m PORTAS REDEFINIDAS"
echo ""
sleep 2s
h
exit
}
edit_dropbear () {
clear
echo ""
echo -e "\033[01;33m ESCOLHA AS PORTAS PARA O DROPBEAR"
local CONF="/etc/default/dropbear"
local NEWCONF="$(cat ${CONF}|grep -v "DROPBEAR_EXTRA_ARGS")"
echo -ne "\033[1;37m NOVA PORTA\033[1;33m:\033[1;37m "; read newports
for PTS in `echo ${newports}`; do
verify_port dropbear "${PTS}" && echo -e "\033[1;33m Port $PTS \033[1;32mOK" || {
echo -e "\033[1;33m Port $PTS \033[1;31mFAIL"
return 1
}
done
rm ${CONF}
while read varline; do
echo -e "${varline}" >> ${CONF}
 if [[ ${varline} = "NO_START=0" ]]; then
 echo -e 'DROPBEAR_EXTRA_ARGS="VAR"' >> ${CONF}
 for NPT in $(echo ${newports}); do
 sed -i "s/VAR/-p ${NPT} VAR/g" ${CONF}
 done
 sed -i "s/VAR//g" ${CONF}
 fi
done <<< "${NEWCONF}"
echo -e "\033[01;37m AGUARDE"
service dropbear restart &>/dev/null
sleep 1s
echo ""
echo -e "\033[01;32m PORTAS REDEFINIDAS"
echo ""
sleep 2s
h
exit
}
edit_openssh () {
clear
echo ""
echo -e "\033[01;33m ESCOLHA AS PORTAS PARA O OPENSSH"
local CONF="/etc/ssh/sshd_config"
local NEWCONF="$(cat ${CONF}|grep -v [Pp]ort)"
echo -ne "\033[1;37m NOVA PORTA\033[1;33m:\033[1;37m "; read newports
for PTS in `echo ${newports}`; do
verify_port sshd "${PTS}" && echo -e "\033[1;33m Port $PTS \033[1;32mOK" || {
echo -e "\033[1;33m Port $PTS \033[1;31mFAIL"
return 1
}
done
rm ${CONF}
for NPT in $(echo ${newports}); do
echo -e "Port ${NPT}" >> ${CONF}
done
while read varline; do
echo -e "${varline}" >> ${CONF}
done <<< "${NEWCONF}"
echo -e "\033[01;37m AGUARDE"
service ssh restart &>/dev/null
service sshd restart &>/dev/null
sleep 1s
echo ""
echo -e "\033[01;32m PORTAS REDEFINIDAS"
echo ""
sleep 2s
h
exit
}
main_fun () {
	[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/portas > /dev/null 2>&1  
clear
echo -e "$linha"
echo -e "\033[01;37m    SERVICOS E PORTAS ATIVAS     \E[0m"
echo -e "$linha"
mine_port
echo -e "$linha"
echo -e "\033[01;37m  SISTEMA DE PORTAS NEW ADM-VPS"
echo -e "$linha"
unset newports
i=0
while read line; do
let i++
          case $line in
          squid|squid3)squid=$i;; 
          apache|apache2)apache=$i;; 
          openvpn)openvpn=$i;; 
          dropbear)dropbear=$i;; 
          sshd)ssh=$i;; 
          esac
done <<< "$(port|cut -d' ' -f1|sort -u)"
echo -ne "\033[01;31m O \033[01;36m-" && echo -e "\033[01;37m [ MENU INICIAL ]"
for((a=1; a<=$i; a++)); do
[[ $squid = $a ]] && echo -ne "\033[01;31m $squid \033[01;36m-" && echo -e "\033[01;32m REDEFINIR PORTAS SQUID"
[[ $apache = $a ]] && echo -ne "\033[01;31m $apache \033[01;36m-" && echo -e "\033[01;32m REDEFINIR PORTA APACHE"
[[ $openvpn = $a ]] && echo -ne "\033[01;31m $openvpn \033[01;36m-" && echo -e "\033[01;32m REDEFINIR PORTA OPENVPN"
[[ $dropbear = $a ]] && echo -ne "\033[01;31m $dropbear \033[01;36m-" && echo -e "\033[01;32m REDEFINIR PORTAS DROPBEAR"
[[ $ssh = $a ]] && echo -ne "\033[01;31m $ssh \033[01;36m-" && echo -e "\033[01;32m REDEFINIR PORTAS SSH"
done
echo -e "$linha"
while true; do
echo -ne "\033[1;37m OPCAO: " && read selection
tput cuu1 && tput dl1
[[ ! -z $squid ]] && [[ $squid = $selection ]] && edit_squid && break
[[ ! -z $apache ]] && [[ $apache = $selection ]] && edit_apache && break
[[ ! -z $openvpn ]] && [[ $openvpn = $selection ]] && edit_openvpn && break
[[ ! -z $dropbear ]] && [[ $dropbear = $selection ]] && edit_dropbear && break
[[ ! -z $ssh ]] && [[ $ssh = $selection ]] && edit_openssh && break
[[ "0" = $selection ]] && h && break

done
#exit 0
}
main_fun