#!/bin/bash
clear
echo ""
echo -e "\033[1;33mDESEJA REINICIAR A VPS?"
echo -ne "\033[01;32m[S/N]\033[1;37m:"; read -e -i s sshsn
[[ "$sshsn" = @(s|S|y|Y) ]] && {
echo ""
echo -e "\033[1;36mPreparando para reiniciar a VPS."
sleep 1s
echo ""
echo -e "\033[1;32mOK"
sleep 1s
sudo reboot
} 