#!/bin/bash
USERS_DATABASE="/home/DATABASE/files/users.db"
BACKUPS="/home/DATABASE/backups"
clear
echo -e "\033[01;36mLISTA DE BACKUPS:\033[01;32m 0: RETORNAR AO MENU."
echo ""
BACKUPS_NUMBER=$(ls $BACKUPS | wc -l)
if [ $BACKUPS_NUMBER = "0" ]; then
  echo -e "\033[01;33mVocê não possui nenhum backup criado no momento!"
  echo ""
  echo -e "\033[01;33mPara prosseguir com esta opção será necessário criar um backup!"
  echo ""
  echo -ne "\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!"
  read ENTER
  usermenu
  exit
else
  for BACKUP in `ls $BACKUPS | sort | sed "s/.zip//g"`; do
    echo -ne "\033[01;33m"; echo $BACKUP
  done
fi
echo ""  
echo -ne "\033[01;36mNome do backup para remover:\033[01;37m "; read NAME
if [ -z $NAME ]; then
  echo ""
  echo -e "\033[01;37;41mVocê não digitou um nome para o backup! Tente novamente.\033[0m"
  sleep 1s
  removebackup
  exit
else
if [ "$NAME" = "0" ]; then
  usermenu
  exit
else
if [[ `ls $BACKUPS | grep -cx "$NAME.zip"` -ne 1 ]]; then
  echo ""
  echo -e "\033[01;37;41mEste backup não existe na lista de backups criados! Tente novamente.\033[0m"
  sleep 1s
  removebackup
  exit
else
  echo ""
  echo -e "\033[01;36mAguarde..."
  sleep 1s
  cd $BACKUPS
  rm -rf $NAME.zip
  clear
  echo -e "\033[01;36mLISTA DE BACKUPS:"; echo ""
  BACKUPS_NUMBER=$(ls $BACKUPS | wc -l)
  if [ $BACKUPS_NUMBER = "0" ]; then
    echo -e "\033[01;33mVocê não possui nenhum backup criado no momento!"
  else
    for BACKUP in `ls $BACKUPS | sort | sed "s/.zip//g"`; do
      echo -ne "\033[01;33m"; echo $BACKUP
    done
  fi
  echo ""
  echo -e "\033[01;32mBackup removido com sucesso!"
  echo -e "\033[01;32mNome do backup: $NAME"
fi
fi
fi
echo ""
echo -ne "\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!"
read ENTER
usermenu
exit