#!/bin/bash
USERS_DATABASE="/root/usuarios.db"
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/userdetalhes > /dev/null 2>&1  
clear
echo ""
echo -e "\E[44;1;37m Usuario         Senha       limite      validade \E[0m"
echo ""
USERS_NUMBER=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)
if [ $USERS_NUMBER = "0" ]; then
	echo ""
  echo -e "\033[01;37mNenhum usuário criado no momento!"
  echo -e "$linha"
  echo -ne "\033[01;36mDESEJA CRIAR UM USUARIO?\033[01;32m [s/n]:\033[01;37m "; read CREATE
      
      if [ "$CREATE" = "s" ]; then   
          criaruser
        exit
      elif [ "$CREATE" = "n" ]; then
          usermenu
        exit
      else
          userdetalhes
        exit
      fi
    fi
  cat $USERS_DATABASE | sort | while read DB; do
  DB1=$(echo $DB | cut -d " " -f1)
  DB3=$(echo $DB | cut -d " " -f2)
 if [[ -e "/etc/SSHPlus/senha/$DB1" ]]; then
    DB2=$(cat /etc/SSHPlus/senha/$DB1)
 else
    DB2="Null"
 fi
  EXPIRE=$(chage -l $DB1 | grep -E "Account expires" | cut -d " " -f3-)
 if [ $EXPIRE = never ] 2> /dev/null
  then
  data="\033[1;33mNunca\033[0m"
 else
  databr="$(date -d "$EXPIRE" +"%Y%m%d")"
  hoje="$(date -d today +"%Y%m%d")"
 if [ $hoje -ge $databr ]
  then
  cont=$(( $cont + 1 ))
  data="\033[1;31mVenceu\033[0m"
 else
  dat="$(date -d"$EXPIRE" '+%Y-%m-%d')"
  data=$(echo -e "$((($(date -ud $dat +%s)-$(date -ud $(date +%Y-%m-%d) +%s))/86400)) \033[1;37mDias\033[0m")
  fi
fi
Usuario=$(printf ' %-15s' "$DB1")
Senha=$(printf '%-13s' "$DB2")
Limite=$(printf '%-10s' "$DB3")
Data=$(printf '%-1s' "$data")
echo -e "\033[1;33m$Usuario \033[1;37m$Senha \033[1;37m$Limite \033[1;32m$Data\033[0m"
echo -e "\033[0m\e[34m==================================================\033[0m"
done
echo ""
echo -e "\033[1;31m ENTER \033[1;33mpara retornar ao \033[1;32mMENU!"
read ENTER
usermenu
exit