#!/bin/bash                      
linha2="\033[0m\e[34m==================================================="
BASE="/home/DATABASE"
memorias () {
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ram=$(printf '%-8s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-13s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_hoje=$(date +'%d/%m/%Y')
if [[ -e /etc/bash.bashrc-bakup ]]; then AutoRun="\033[1;31m[\033[1;37mON\033[1;31m]"
elif [[ -e /etc/bash.bashrc ]]; then AutoRun="\033[1;37m[\033[1;31mOFF\033[1;37m]"
fi
_on="\033[1;31m[\033[1;37mON\033[1;31m]"
_off="\033[1;37m[\033[1;31mOFF\033[1;37m]"
unset pid_badvpn && pid_badvpn=$(netstat -nlpt | egrep -o udpgw)
[[ "$pid_badvpn" != "" ]] && _badvpn="$_on" || _badvpn="$_off"
[[ `grep -c "^#ADM" /etc/sysctl.conf` -eq 0 ]] && _tcpspeed="$_off" || _tcpspeed="$_on"
[[ ! -e /usr/lib/ADMNETFREE ]] && rm -rf /bin/usermenu > /dev/null 2>&1
[[ ! -e /etc/ADMVPS ]] && rm -rf /bin/usermenu > /dev/null 2>&1  
_total=$(awk  -F : '$3 >= 500 {print  $1}'  /etc/passwd | grep -v "nobody" | sort | wc -l)
[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;31m[\033[1;37mON\033[1;31m]" || _autorun="\033[1;37m[\033[1;31mOFF\033[1;37m]"
stsl=$(ps x | grep "limiterstart"|grep -v grep > /dev/null && echo -e "\033[1;31m[\033[1;37mON\033[1;31m]" || echo -e "\033[1;37m[\033[1;31mOFF\033[1;37m]")
os_system () {
system=$(echo $(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //'))
echo $system|awk '{print $1, $2}'
}
BLOCK="$(wc -l /home/DATABASE/ADMVPS-userlock | awk '{print $1}')"
__IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
echo -e "\033[1;32m   >>>>>>>>\033[01;36m GERENCIADOR \033[01;31m[\033[01;36m NEW ADM-VPS \033[01;31m]\033[1;32m <<<<<<<< "

echo -e "$linha2"
echo -e "\033[1;32m  DATA\033[1;37m/\033[1;32mHORA       MEMORIA RAM    SISTEMA\033[1;37m/\033[1;32mIP "
echo -e "\033[1;31m  DIA\033[1;32m:\033[1;37m$_hoje \033[1;31m TOTAL\033[1;32m:\033[1;37m$_ram\033[1;31m OS\033[1;32m:\033[1;37m$_system"
echo -e "\033[1;31m  HORA\033[1;32m:\033[1;37m$_hora  \033[1;31m EM USO\033[1;32m:\033[1;37m$_usor\033[1;31mIP\033[1;32m:\033[1;37m$__IP"
echo -e "$linha2"
STATUS_NUMBER=$(ps -x | grep -c "limiterstart")
if [ $STATUS_NUMBER -gt "1" ]; then
_userexp=$(printf '%-6s' "$(cat ${BASE}/USRexpired)")
_online=$(printf '%-5s' "$(cat ${BASE}/USRonlines)")
_block=$(printf '%-5s' "$BLOCK")
total=$(printf '%-6s' "$_total")
echo -e "\033[1;36m  ONLINE\033[1;32m:\033[1;37m$_online\033[1;36mVENCIDOS\033[1;32m:\033[1;31m$_userexp\033[1;36mBLOCK\033[1;32m:\033[1;31m$_block\033[1;36mTOTAL\033[1;32m:\033[1;37m$total  \n$linha2 \033[0m"
else
_userexp=$(printf '%-6s' "OFF")
_online=$(printf '%-5s' "OFF")
_block=$(printf '%-5s' "OFF")
total=$(printf '%-6s' "OFF")
echo -e "\033[1;36m  ONLINE\033[1;32m:\033[1;31m$_online\033[1;36mVENCIDOS\033[1;32m:\033[1;31m$_userexp\033[1;36mBLOCK\033[1;32m:\033[1;31m$_block\033[1;36mTOTAL\033[1;32m:\033[1;31m$total  \n$linha2 \033[0m"
fi
}

clear
echo -e "$linha2"
memorias
echo -e "\033[01;31m  O\033[01;36m -\033[01;37m [ SAIR DO MENU ]   \033[01;31m14\033[01;36m -\033[1;32m BANNER SSH"
echo -e "\033[01;31m  1\033[01;36m -\033[1;32m NOVO USUARIO       \033[01;31m15\033[01;36m -\033[1;32m LIMPAR MEMÓRIA"
echo -e "\033[01;31m  2\033[01;36m -\033[1;32m USUARIO TESTE      \033[01;31m16\033[01;36m -\033[1;32m LIMITER\033[1;37m/\033[1;32mMON $stsl"
echo -e "\033[01;31m  3\033[01;36m -\033[1;32m REMOVER USUARIO    \033[01;31m17\033[01;36m -\033[1;32m BAD UDP $_badvpn"
echo -e "\033[01;31m  4\033[01;36m -\033[1;32m MONITORAR ONLINE   \033[01;31m18\033[01;36m -\033[1;32m TCP SPEED $_tcpspeed"
echo -e "\033[01;31m  5\033[01;36m -\033[1;32m ALTERAR VALIDADE   \033[01;31m19\033[01;36m -\033[1;32m AUTO INICIAR $AutoRun"
echo -e "\033[01;31m  6\033[01;36m -\033[1;32m ALTERAR SENHA      \033[01;31m20\033[01;36m -\033[1;32m VELOCIDADE VPS"
echo -e "\033[01;31m  7\033[01;36m -\033[1;32m ALTERAR LIMITE     \033[01;31m21\033[01;36m -\033[1;32m INFORMAÇÕES VPS"
echo -e "\033[01;31m  8\033[01;36m -\033[1;32m DETALHES USUARIOS  \033[01;31m22\033[01;36m -\033[1;32m USO DE BANDA"
echo -e "\033[01;31m  9\033[01;36m -\033[1;32m REMOVER VENCIDOS   \033[01;31m23\033[01;36m -\033[1;32m MUDAR SENHA ROOT"
echo -e "\033[01;31m 10\033[01;36m -\033[1;32m BLOQUEAR USUARIOS  \033[01;31m24\033[01;36m -\033[1;32m ALTERAR NOME VPS"
echo -e "\033[01;31m 11\033[01;36m -\033[1;32m MENU INSTALAÇÕES   \033[01;31m25\033[01;36m -\033[1;32m REINICIAR VPS"
echo -e "\033[01;31m 12\033[01;36m -\033[1;32m CONFIGURAR PORTAS  \033[01;31m26\033[01;36m -\033[1;32m REINICIAR SERVIÇOS"
echo -e "\033[01;31m 13\033[01;36m -\033[1;32m GERENCIAR BACKUPS  \033[01;31m27\033[01;36m -\033[1;32m REMOVER\033[01;31m [\033[01;37mSCRIPTS\033[01;31m]"
echo -e "$linha2"
echo -ne "\033[1;37m OPÇÃO \033[1;31m0\033[1;36m-\033[1;31m27\033[1;37m:"; read NUMBERS
case $NUMBERS in
0) 
exit;;
1) criaruser
exit
;;
2) userteste
exit
;;
3) removeuser
exit
;;
4) monitoring
exit
;;
5) mudardata
exit
;;
6) mudarsenha
exit
;;
7) limiterconex
exit
;;
8) userdetalhes
exit
;;  
9) expirados
exit
;;
10) blockuser
exit
;;
11) instalar
exit
;;
12) portas
exit
;;
13) menubackup
exit
;;
14) bannerssh
exit
;;
15) limparcache
exit
;;
16) limitermenu
exit
;;
17) badudp
exit
;;
18) tcpspeed
exit
;;
19) autorun
exit
;;
20) clear
velocidade
exit
;;
21) informacoes
exit
;;
22)
clear
echo -e "\033[1;32mPARA SAIR CLICK CTRL + C\033[1;36m"
sleep 1.5
nload
h
exit
;;
23) senhart
exit
;;
24) hostnamevps
exit
;;
25) reiniciar_vps;;
26) rserv
exit
;;
27) uninstall
exit
;;
*) usermenu
exit
;;
esac




